name: Performance test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '14' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build:packages

      - name: Run tests
        run: NODE_ENV=production yarn test:perf
        env:
          PERF_SANITY_WRITE_TOKEN: ${{ secrets.PERF_SANITY_WRITE_TOKEN }}

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: perf
          path: ${{ github.workspace }}/perf/artifacts
