name: Performance tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [ '14' ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn install

      - name: Run tests
        run: NODE_ENV=production yarn test:perf
        env:
          PERF_SANITY_WRITE_TOKEN: ${{ secrets.PERF_SANITY_WRITE_TOKEN }}

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: perf
          path: ${{ github.workspace }}/perf/artifacts
